#!/usr/bin/env bash
echo uninstalling bbp v$BISBASHPROMPTVERSION
echo "removing source calls in ~/.bashrc"
grep -v "source ~/.bbp" ~/.bashrc > tmp
mv tmp ~/.bashrc
echo "removing ~/.bbp"
rm ~/.bbp
echo "rerunning ~/.bashrc"
source ~/.bashrc