#!/bin/sh
echo "installing bbp version 3"
source .installbbp
echo "setting ~/.bbp"
echo "PS1='\[\e[36m\]\s\[\e[0m\] \[\e[34;1m\]\v\[\e[0m\] | \[\e[92;5m\]\#\[\e[0m\]/\[\e[92m\]\!\[\e[0m\] [\[\e[32m\]\u@\H\[\e[0m\]:\[\e[34m\]\w\[\e[0m\]] {\[\e[93m\]$?\[\e[0m\]} \$ '" > ~/.bbp
echo "rerunning ~/.bashrc"
source ~/.bashrc
