#!/bin/sh
export BISBASHPROMPTVERSION=6
echo "installing bbp version $BISBASHPROMPTVERSION"
source ./src/installbbp
echo "setting ~/.bbp"
echo "export BISBASHPROMPTVERSION=$BISBASHPROMPTVERSION" > ~/.bbp
echo "PS1='( \[\e[32m\]\s\[\e[0m\] \[\e[34;1m\]\v\[\e[0m\] | \[\e[35m\]bbp \[\e[34;1m\]v${BISBASHPROMPTVERSION:-?}\[\e[0m\] ) \[\e[32m\]\u@\h\[\e[0m\]:\[\e[34m\]\w\[\e[0m\]\$ '" >> ~/.bbp
echo "rerunning ~/.bashrc"
source ~/.bashrc