#!/usr/bin/env bash
export BISBASHPROMPTVERSION=15
echo "installing bbp version $BISBASHPROMPTVERSION"
source ./src/installbbp
echo "setting ~/.bbp"
echo "export BISBASHPROMPTVERSION=$BISBASHPROMPTVERSION" > ~/.bbp
echo "PS1='\[\e[96m\]\s\[\e[0m\] \[\e[92m\]\u\[\e[0m\] \[\e[94m\]\w\[\e[0m\] \\$ '" >> ~/.bbp
echo "rerunning ~/.bashrc"
source ~/.bashrc