#!/bin/sh
export BISBASHPROMPTVERSION=2
echo "installing bbp version $BISBASHPROMPTVERSION"
source ./src/installbbp
echo "setting ~/.bbp"
echo "export BISBASHPROMPTVERSION=$BISBASHPROMPTVERSION" > ~/.bbp
echo "PS1='( \[\e[36m\]\s\[\e[0m\] \[\e[94;1m\]\V\[\e[0m\] ) \[\e[92;5m\]#\#\[\e[0m\]/\[\e[92m\]#\!\[\e[0m\] \[\e[33m\]\t\[\e[0m\] [\[\e[32m\]\u@\H\[\e[0m\]:\[\e[34m\]\w\[\e[0m\]] {\[\e[35m\]Exit Code: \[\e[93m\]$?\[\e[0m\]} \$ '" >> ~/.bbp
echo "rerunning ~/.bashrc"
source ~/.bashrc
