#!/usr/bin/env bash
export BISBASHPROMPTVERSION=8
echo "installing bbp version $BISBASHPROMPTVERSION"
source ./src/installbbp
echo "setting ~/.bbp"
echo "export BISBASHPROMPTVERSION=$BISBASHPROMPTVERSION" > ~/.bbp
echo "PS1='\[\e[34m\]\w\[\e[0m\] \$> '" >> ~/.bbp
echo "rerunning ~/.bashrc"
source ~/.bashrc